index:
    path: /
    methods: ["GET"]
    controller: App\Controller\DefaultController::index
oublipass :
    path: /oublipass
    methods: ["GET", "POST"]
    controller: App\Controller\OubliPassController::index

resetpass :
    path: /resetpass
    methods: ["GET", "POST"]
    controller: App\Controller\ResetPassController::index

tenant:
    path: /tenant
    methods: [ "GET", "POST" ]
    controller: App\Controller\TenantController::index


